/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 window.glb --transform --shadows --resolution 512 --keepmeshes --instance --types
Files: window.glb [236.23KB] > /Users/magdysaber/Desktop/magdysaber.com/public/window-transformed.glb [38.44KB] (84%)
Author: AleixoAlonso (https://sketchfab.com/AleixoAlonso)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/residential-window-ae11104237314463a61251fd46ded4b4
Title: Residential Window
*/

import { useGLTF, useScroll } from '@react-three/drei';
import { useFrame } from '@react-three/fiber';
import { useRef } from 'react';
import * as THREE from 'three';
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    ['#WIN0003_Frame_#WIN0003_Textures_0']: THREE.Mesh
    ['#WIN0003_Window_#WIN0003_Textures_0']: THREE.Mesh
    ['#WIN0003_Handle_#WIN0003_Textures_0']: THREE.Mesh
  }
  materials: {
    WIN0003_Textures: THREE.MeshPhysicalMaterial
  }
}
const WindowModel = (props: Partial<THREE.Object3D>) => {
  const handleRef = useRef<THREE.Mesh>(null);
  const windowRef = useRef<THREE.Mesh>(null);
  const modelRef = useRef<THREE.Group>(null);

  const { nodes, materials } = useGLTF('models/window.glb', true ) as unknown as GLTFResult
  const data = useScroll();
  useFrame(() => {
    // The window is an opening-scene object. Once Experience has taken over,
    // keeping its frame in the scene can leave a stray white edge across the
    // contact area as the camera passes it.
    if (modelRef.current) {
      modelRef.current.visible = data.offset < 0.8;
      if (!modelRef.current.visible) return;
    }

    // Open while the camera is descending through the sky, rather than
    // withholding the door until most of the hero scroll has elapsed.
    const b = data.range(0.3, 0.14);
    const c = data.range(0.4, 0.14);

    if (handleRef.current) {
      handleRef.current.rotation.y = -0.5 * Math.PI * b;
    }
    if (windowRef.current) {
      windowRef.current.rotation.z = 0.5 * Math.PI * c;
    }
  });

  return (
    <group ref={modelRef} {...props} dispose={null}>
      <group rotation={[0, Math.PI, Math.PI]}>
        <mesh
          geometry={nodes['#WIN0003_Frame_#WIN0003_Textures_0'].geometry}
          material={materials.WIN0003_Textures}
        />
        <group position={[0.441, -0.039, 0.082]}
          ref={windowRef}>
          <mesh
            geometry={nodes['#WIN0003_Window_#WIN0003_Textures_0'].geometry}
            material={materials.WIN0003_Textures}/>
          <mesh ref={handleRef}
            geometry={nodes['#WIN0003_Handle_#WIN0003_Textures_0'].geometry}
            material={materials.WIN0003_Textures}
            position={[-0.84, -0.018, 0.55]} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('models/window.glb');

export default WindowModel;
